name: book_library_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  path: ^1.8.0
  idb_shim: ^2.0.0+2
  provider: ^6.0.0
  image_picker: ^0.8.4+2
  uuid: ^3.0.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/book_app_logo.jpg
    - assets/screenshots/add_screen.jpg
    - assets/screenshots/book_detail_view.jpg
    - assets/screenshots/edit_screen.jpg
    - assets/screenshots/home_screen.jpg
    - assets/screenshots/search_screen.jpg
    - assets/screenshots/settings_view.jpg
    - assets/screenshots/welcome_screen.jpg
    - assets/icons/apple-logo.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/instagram.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
